version: '3'
services:
  qgis:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
        KART_VERSION: ${KART_VERSION}
    tty: true
    volumes:
      - ${GITHUB_WORKSPACE}:/usr/src
