name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    name: "Release on tag"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Build package
        run: |
          python helper.py "${GITHUB_REF/refs\/tags\//}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            kart-*.zip"
