name: Testing

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  # Run unit tests
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        qgis_version: [release-3_16, 'release-3_22', latest]
      fail-fast: false

    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test on QGIS
        run: >
          docker-compose -f .docker/docker-compose.gh.yml
          run qgis /usr/src/.docker/run-docker-tests.sh
